[workspace]
authors = ["PÃ¤r Larsson <par.larsson.medbio@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "qz"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
spring = ">=1.1.1,<2"
megahit = ">=1.2.9,<2"
numpy = ">=2.4.2,<3"
tensorly = ">=0.8.2,<0.9"
scipy = ">=1.17.0,<2"
