[workspace]
authors = ["PÃ¤r Larsson <par.larsson.medbio@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "qz"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
spring = ">=1.1.1,<2"
