[package]
name = "qz-python"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Python bindings for QZ FASTQ compression"

[lib]
name = "qz"
crate-type = ["cdylib"]

[dependencies]
qz-lib.workspace = true
pyo3.workspace = true
